spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dali?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture

logging:
  level:
    org.hibernate.SQL: debug