spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dali?useUnicode=true&characterEncoding=utf-8
    username: ${MARIA_DB_ID}
    password: ${MARIA_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug